[book]
authors = ["Fuel Labs"]
language = "en"
multilingual = false
src = "text"
title = "The Fuel RFC Book"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/FuelLabs/rfcs"

[rust]
edition = "2018"
